version : '3'
services:

    nginx:
        build: .
        image: newhr/http2-server:latest
        hostname: nginx
        restart : always
        network_mode: host
        container_name: nginx

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        volumes:
            - ./etc/nginx:/etc/nginx
            - ./etc/letsencrypt:/etc/letsencrypt
            - ./pagespeed:/var/pagespeed
            - /www/sites:/www/sites
            - /var/log:/var/log

        environment:
            - TIMEZONE=Europe/Moscow
            - LETSENCRYPT=true
            - LE_EMAIL=major@new.hr
            - LE_DNAME=newhr.org
            - LE_RT=70d

#EOF#